package com.wdd.test.bean;

import java.util.Date;

public class Sysuserinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.userid
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.agentID
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String agentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.password
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.usertype
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.username
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.sex
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.cardID
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.mobile
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.nickname
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.is_nickname
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String isNickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.status
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.createtime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.updatetime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column f_sysuserinfo.pwd_last_datetime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    private Date pwdLastDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.userid
     *
     * @return the value of f_sysuserinfo.userid
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.userid
     *
     * @param userid the value for f_sysuserinfo.userid
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.agentID
     *
     * @return the value of f_sysuserinfo.agentID
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getAgentid() {
        return agentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.agentID
     *
     * @param agentid the value for f_sysuserinfo.agentID
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setAgentid(String agentid) {
        this.agentid = agentid == null ? null : agentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.password
     *
     * @return the value of f_sysuserinfo.password
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.password
     *
     * @param password the value for f_sysuserinfo.password
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.usertype
     *
     * @return the value of f_sysuserinfo.usertype
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.usertype
     *
     * @param usertype the value for f_sysuserinfo.usertype
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.username
     *
     * @return the value of f_sysuserinfo.username
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.username
     *
     * @param username the value for f_sysuserinfo.username
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.sex
     *
     * @return the value of f_sysuserinfo.sex
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.sex
     *
     * @param sex the value for f_sysuserinfo.sex
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.cardID
     *
     * @return the value of f_sysuserinfo.cardID
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.cardID
     *
     * @param cardid the value for f_sysuserinfo.cardID
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.mobile
     *
     * @return the value of f_sysuserinfo.mobile
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.mobile
     *
     * @param mobile the value for f_sysuserinfo.mobile
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.nickname
     *
     * @return the value of f_sysuserinfo.nickname
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.nickname
     *
     * @param nickname the value for f_sysuserinfo.nickname
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.is_nickname
     *
     * @return the value of f_sysuserinfo.is_nickname
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getIsNickname() {
        return isNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.is_nickname
     *
     * @param isNickname the value for f_sysuserinfo.is_nickname
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setIsNickname(String isNickname) {
        this.isNickname = isNickname == null ? null : isNickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.status
     *
     * @return the value of f_sysuserinfo.status
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.status
     *
     * @param status the value for f_sysuserinfo.status
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.createtime
     *
     * @return the value of f_sysuserinfo.createtime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.createtime
     *
     * @param createtime the value for f_sysuserinfo.createtime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.updatetime
     *
     * @return the value of f_sysuserinfo.updatetime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.updatetime
     *
     * @param updatetime the value for f_sysuserinfo.updatetime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column f_sysuserinfo.pwd_last_datetime
     *
     * @return the value of f_sysuserinfo.pwd_last_datetime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public Date getPwdLastDatetime() {
        return pwdLastDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column f_sysuserinfo.pwd_last_datetime
     *
     * @param pwdLastDatetime the value for f_sysuserinfo.pwd_last_datetime
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    public void setPwdLastDatetime(Date pwdLastDatetime) {
        this.pwdLastDatetime = pwdLastDatetime;
    }
}