package com.wdd.test.dao;

import com.wdd.test.bean.Sysuserinfo;
import com.wdd.test.bean.SysuserinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysuserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int countByExample(SysuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int deleteByExample(SysuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int insert(Sysuserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int insertSelective(Sysuserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    List<Sysuserinfo> selectByExample(SysuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    Sysuserinfo selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sysuserinfo record, @Param("example") SysuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int updateByExample(@Param("record") Sysuserinfo record, @Param("example") SysuserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int updateByPrimaryKeySelective(Sysuserinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table f_sysuserinfo
     *
     * @mbggenerated Tue Jan 30 18:29:43 CST 2018
     */
    int updateByPrimaryKey(Sysuserinfo record);
}